### ISSUE TITLE
Chapter 2 - Introducing Auto Layout

### ISSUE THREAD

**Issue by zweckApp** [secondgear/Achieving-Zen-With-Auto-Layout#6]
In PDF version only: Right under figure 3 the code sample is cut off at the right side of the page.
"override func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator: coordinator: U..."

**Comment by justin** [comment]
Fixed. Thanks!

**Comment by atecle** [comment]
Hey Justin - just bought your book yesterday. Still seeing this issue in the PDF
![issue 6](https://cloud.githubusercontent.com/assets/3269331/11820862/8df1e3ba-a334-11e5-8b7c-a8ec52df4b89.png)

**Comment by justin** [comment]
Thanks. I'll see if i can get that fixed and spin up a new build soon. waiting to get a few more chapters back from copy editor.
